---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  type: ClusterIP
  selector:
    app: echoserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP