---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argocd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.16.1
    helm:
      releaseName: argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd